version: '3'

services:
  chirpstack-ran-bridge:
    build: .
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}

      - CHIRPSTACK_API_TOKEN
      - CHIRPSTACK_API_GRPC_HOST=${CHIRPSTACK_API_GRPC_HOST:-chirpstack-application-server}
      - CHIRPSTACK_API_GRPC_PORT=${CHIRPSTACK_API_GRPC_PORT:-8080}
      - CHIRPSTACK_API_GRPC_SECURE
      - CHIRPSTACK_API_GRPC_CERT_PATH

      - CHIRPSTACK_MQTT_SERVER_URI=${CHIRPSTACK_MQTT_SERVER_URI:-mqtt://mosquitto:1883}

      - CHIRPSTACK_MATCH_TAGS=${CHIRPSTACK_MATCH_TAGS:-everynet=true}
      - CHIRPSTACK_DEVICES_REFRESH_PERIOD=${CHIRPSTACK_DEVICES_REFRESH_PERIOD:-300}
      - CHIRPSTACK_ORGANIZATION_ID=${CHIRPSTACK_ORGANIZATION_ID:-0}

      - RAN_API_URL
      - RAN_TOKEN

      - SKIP_RAN_ORPHANED_DEVICES

      - HEALTHCHECK_SERVER_HOST=${HEALTHCHECK_SERVER_HOST:-0.0.0.0}
      - HEALTHCHECK_SERVER_PORT=${HEALTHCHECK_SERVER_PORT:-9090}
    logging:
      driver: 'json-file'
      options:
        max-size: "100m"
        max-file: "1"
    depends_on:
      - chirpstack-application-server
      - chirpstack-network-server

